name: cicd pipeline
on:
 push:
  branches: ['main']
 workflow_dispatch: 
jobs:
 first:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v4
  - name: first pipeline
    run: echo 'Hello new pipeline'
